spring:
  application:
    name: stock-trading
  data:
    mongodb:
      host: localhost
      port: 27017
      username: admin
      password: 123456
      database: stocks
server:
  port: 8060

clients:
  stockMarket:
    baseUrl: "http://localhost:8050"


