spring:
  application:
    name: stock-trading
  data:
    mongodb:
      uri: mongodb://admin:123456@localhost:27017/
      database: stocks
server:
  port: 8060

clients:
  stockMarket:
    baseUrl: "http://localhost:8050"


